name: Auto Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 1 * *'  # Runs monthly on the 1st at 08:00 UTC

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Make changes (e.g., create daily log)
      run: |
        e echo "TDS Graded Assignment runs: $(date -u) TDSGA" >> daily-log.txt

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto commit at $(date -u)" || echo "Nothing to commit"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Kriti0613/daily-commit-workflow.git
        git push
