name: Auto Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 4 * * *' 

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo with PAT
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Make changes (e.g., create daily log)
      run: |
        echo "TDS Graded Assignment runs: $(date -u) TDSGA" >> daily-log.txt

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "23f1001363@ds.study.iitm.ac.in"
        git config user.email "23f1001363@ds.study.iitm.ac.in"
        git add .
        git commit -m "Auto commit at $(date -u)" || echo "Nothing to commit"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/Kriti0613/daily-commit-workflow.git
        git push
